export type Artigo = {
  slug: string;
  titulo: string;
  autor?: string;
  paragrafos: string[];
  notas?: string[];
};

export const artigos: Artigo[] = [
  {
    slug: "porque-estudar-teologia",
    titulo: "Porque estudar teologia",
    autor: "Professora Vera Rodrigues Lima",
    paragrafos: [
      "O estudo da teologia é uma tarefa para todo cristão. Erramos quando não nos esforçamos na leitura e reflexão das escrituras. Jesus nos adverte nos textos: Mt 22:29 – Mc 12:24 - 14:49, sobre a questão e, portanto, pecamos quando não damos crédito a ela. Há sérios riscos de cairmos no engano das heresias ou de interpretarmos de forma errada os textos bíblicos.",
      "Ao longo de suas vidas cristãs, algumas pessoas falam e agem como se a fé e a razão fossem verdades opostas. Acreditam que em seu relacionamento com Deus, necessitam apenas da fé e ignoram que a Lei de Moisés envolvia também aspectos lógicos e racionais, conforme podemos perceber nas ordens de Deus a Josué: “Tão-somente sê forte e mui corajoso para teres o cuidado de fazer segundo toda a lei que meu servo Moisés te ordenou. Dela não te desvies, nem para a direita nem para a esquerda, para que sejas bem-sucedido por onde andares. Não cesses de falar deste Livro da Lei; antes, medita nele dia e noite, para que tenhas cuidado de fazer segundo tudo quanto nele está escrito; então, farás prosperar o teu caminho e serás bem-sucedido”. De acordo com esse texto, Josué deveria não apenas aceitar (pela fé) a vontade de Deus, mas igualmente conduzir-se de modo obediente (razão) à deliberação de Deus. Suas atitudes e conduta deveriam ser resultado de um estudo contínuo e racional de toda a lei dada a Moisés.",
      "Uma teologia sadia, livre de pressupostos humanos, feita com análise cautelosa, visto que há várias correntes teológicas em nosso meio, certamente nos ajudará a encontrar um caminho mais seguro na busca da maturidade espiritual. Por isso é urgente e necessário estudarmos e compreendermos a teologia expressa na Sagrada Escritura para que possamos servir a Deus, de modo adequado e conforme ele mesmo prescreveu em sua Palavra.",
      "Para acrescentar e potencializar o resultado do estudo devemos nos aplicar a reflexão das escrituras, acompanhado de oração, humildade e submissão ao Espírito Santo. O conjunto dessas ações resultará em uma compreensão mais profunda sobre a pessoa de Jesus Cristo, como também nos dá maior clareza quanto a nossa identidade cristã, nos levando ao exercício de uma espiritualidade mais centralizada em Cristo.",
    ],
  },
  {
    slug: "o-pensamento-de-paulo-e-a-soberania-de-deus",
    titulo: "O pensamento de Paulo e a Soberania de Deus",
    paragrafos: [
      "A palavra “soberania” não aparece no texto sagrado, mas a ideia está explicita em toda a Bíblia, como na carta aos Romanos 11:33-36:",
      "Ó profundidade das riquezas, tanto da sabedoria, como da ciência de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis, os seus caminhos! Porque quem compreendeu o intento do Senhor? Ou quem foi seu conselheiro? Ou quem lhe deu primeiro a ele, para que lhe seja recompensado? Porque dele, e por ele, e para ele são todas as coisas; glória, pois, a ele eternamente. Amém!",
      "Nas saudações finais desta mesma carta Paulo reporta ao evangelho de Jesus Cristo como “a revelação do mistério que desde tempos eternos esteve oculto” (Rm 16:25) e demonstra o que Deus, com base nos seus decretos, pensou sobre a salvação da humanidade na eternidade passada e assim determinou as ações que no devido tempo deveriam acontecer.",
      "Os resultados da salvação do pecador estão inseridos no “decreto” de Deus que antecipadamente previu que os salvos deveriam ser conforme “à imagem de seu Filho” e isto por meio de um plano estabelecido que envolve conhecimento, predestinação, chamado, justificação e a glorificação (Rm 8:28-30).",
      "Quando Paulo de reporta aos “tempos eternos” está trazendo a memória que no princípio, nada havia ou existia além de Deus para influenciá-lo quando Ele decretou, e o fez livremente e voluntariamente, ou seja, soberanamente estabeleceu sua vontade.",
      "Pelo contrário, repetimos, os decretos de Deus são baseados em Seu sábio e santo conselho. Sendo sumamente sábio, conhecendo o fim e o princípio, sabendo que o pecado viria (já que Ele havia resolvido permitir sua vinda), sabendo qual seria a natureza do pecado e como Ele teria que lidar com ele se fosse salvar alguém, Ele baseou Seus planos em todo Seu conhecimento e compreensão. Sendo perfeitamente santo, e incapaz de parcialidade ou injustiça, Ele fez Seus planos de acordo com o que é absolutamente certo. Ele pode salvar o pecador apenas se, ao fazê-lo, puder permanecer absolutamente justo (Rm 3:25). É baseado em Sua sabedoria e santidade, portanto, que Ele fez os decretos, tanto os eficazes como os permissivos (1)",
      "O entendimento é que na sua soberania Deus “que desde tempos eternos” Seu eterno propósito, assim como planejado, à medida que a história se desenvolve eles vão acontecendo. Razão pela qual quando Paulo aborda o plano da redenção, faze-o informando que faz parte do “evangelho de Deus” (Rm 1:1; 15:16) que é o “mistério que desde tempos eternos esteve oculto” (Rm 16:25), entretanto, “o qual antes havia prometido pelos seus profetas nas Santas Escrituras” (Rm 1:2).",
      "Quando Paulo apresenta seu apostolado e o propósito do mesmo, ele demonstra a soberania da Trindade e diz “que eu seja ministro de Jesus Cristo entre os gentios, ministrando o evangelho de Deus, para que seja agradável a oferta dos gentios, santificada pelo Espírito Santo” (Rm 15:16), e toda a vontade de Deus está inserida no evangelho e em momento algum abre mão de nenhuma das prerrogativas dos seus atributos e dons para salvar os pecadores.",
      "Paulo faz duas citações de que o evangelho é Deus (Rm 1:1) e que Jesus Cristo ressurreto é a expressão maior do “evangelho de Deus”. O enfoque é que Deus soberanamente apresenta por meio do evangelho o poder que pode operar a salvação no pecador.",
      "Na doxologia de Paulo inicialmente descrita, arroga estar diante de um Deus que é insondável em sabedoria quando executa os seus juízos e inescrutável nos caminhos da sua ciência, informando que Deus de maneira gloriosa e eterna tem toda a criação sob seu controle absoluto: “Porque dele e por ele, e para ele são todas as coisas”. Dentre “todas as coisas” está a “justificação do pecador” que lhe possibilita reconciliar-se com Deus.",
      "Somente podemos tomar conhecimento da soberania de Deus, se conhecermos a Deus.",
      "Deus é o próprio ser e, portanto, além de todas as coisas existentes. Situa-se além do conhecimento porque o conhecimento pressupõe divisão entre sujeito e objeto. [...] Ele reúnem-se todos os poderes de ser. [...] É o princípio universal de todas as coisas particulares, de tudo o que possui ser. Paul Tillich (2)",
      "E uma das maneiras de se conhecer a Deus, é conhecer o que Bíblia descreve acerca Dele. Neste sentido a teologia sistemática é um instrumento valioso. Pois é necessário examinar o assunto diretamente e plenamente a luz da Escrituras, e, é preciso colocar em ordem tudo o que Bíblia diz em um sistema organizado.",
      "E quanto analisamos e estudamos sobre a natureza de Deus, precisamos fazer pelo menos sobre duas perspectivas que são essência de Deus e atributos de Deus. Quanto a essência devemos ter entendimento doutrinal no que diz respeito a espiritualidade, a auto existência, imensidão e eternidade de Deus; por outro lado, os atributos devem ser pontuados, pelo menos em duas etapas, os absolutos e relativos.",
      "É imperioso saber que quando a Bíblia trata da natureza de Deus estamos diante de uma Unidade e Trindade, mesmo o termo Trindade não estar cunhado nas Escrituras Sagradas, entretanto, a ideia está implícita e explicita ao longo dos registros. O Novo Testamento, escrito após o evento histórico da encarnação do Verbo, as narrativas são constantes com Pai, Jesus Cristo e o Espirito Santo (Rm 15:16). As três pessoas em uma mesma essência, não havendo diferença de glória, poder, ou extensão da existência, mas simplesmente de ordem.",
    ],
    notas: [
      "1. Palestras em Teologia Sistemática; Henry Clarence Thiessem; IBR; 1994; P. 98",
      "2. História do Pensamento Cristão; Paul Tillich; ASTE, 2007; p. 76",
    ],
  },
  {
    slug: "o-chamado-em-cristo-para-a-vida-eterna",
    titulo: "O chamado em Cristo para a vida eterna",
    autor: "Pr Sebastião Otávio",
    paragrafos: [
      "A Ekklesia de Cristo é composta de pessoas que atenderam o “ekklatoi” divino e saíram “para fora de si mesmos e para a reunião de Cristo em Deus”. Essa ideia permeia nos Escritos do Novo Testamento e o “eschaton” aborda as últimas coisas no plano de Deus para com os homens. A Igreja em si tem um caráter profético, histórico e universal descrito no Apocalipse (capítulos 2 e 3) em suas várias fases, tipos, estados e condições, com ênfase nas condições espirituais, comportamento para com o mundo, consigo mesma e o Senhor Jesus Cristo.",
      "A impressionante expressão de Paulo na carta aos Colossenses “Cristo que é a nossa vida” (Cl 3:3) deixa claro que Cristo é a cabeça federal de uma nova ordem de seres humanos, destinados a vida eterna, desde o momento do acesso a graça pelo sacrifício do próprio Cristo na cruz (Rm 5:2).",
      "Trazemos ainda na vida presente os estigmas da velha natureza herdada de Adão, mas já está implantada em nós a natureza divina (1 Pe 1:3-4; 1:22-25). A natureza recebida de Adão é caracterizada pelas expressões “velho homem” e “carne” que podem ser analisadas na seguinte perspectiva: Fator espiritual, demonstra que somos pecadores e é algo sempre presente, embora já libertados do poder do pecado. A outra expressão, Fator corporal, evidência que somos mortais e a mortalidade (morte física) influencia no futuro humano.",
      "A expressão paulina “a vida que agora vivo na carne” (Gl 2:20) traça a linha divisória do antigo viver alienado da graça e justiça de Deus (Gl 2:21). Em suas cartas de maneira explicita e implícita, demonstra a sua esperança escatológica, o que podemos chamar de filosofia de vida cristã de Paulo, pois temos o seu estilo de vida, atitudes, modo de ver a vida presente e a futura, e maneira de avaliar as circunstancias e pessoas.",
      "As palavras paulinas aos colossenses (3.4) “quando Cristo que é a nossa vida, se manifestar, então também vós vos manifestareis com ele em glória” implica que “eschaton” no contexto da doutrina bíblica, tem a ver com a projeção do futuro de todas as premissas assentadas nas lições previas, tem como foco a consumação que envolve o destino do homem, tanto do salvo, como do ímpio.",
      "Esperança em Cristo é a esperança em sua vinda (Cl 1:5), pois junto com a sua glória será manifesta a nossa, como membros de seu corpo já a temos em segredo (1 Jo 3:2). Para o salvo a esperança no advento futuro de Cristo não é mero apêndice à nossa crença Nele, mas é a nossa coroa.",
      "A nossa crença em Cristo faz nos acreditar nas suas palavras “virei outra vez e vos levarei para mim mesmo, para que onde eu estiver estejais vós também” (Jo 14:3), bem como nas garantias apresentadas “eu rogarei ao Pai, e ele vos dará outro Consolador, para que fique convosco para sempre” (Jo 14:16) e é por isso que Paulo disse que fomos selados com o Espírito Santo da promessa o qual é o penhor da nossa herança. (Ef 1:13,14)",
      "Fundamentados nessa esperança não temos dificuldade de aguardamos a consumação da obra de Cristo, quando acontecerá a nossa completa união com Ele glorificado e a nossa assimilação a Ele, pois o Espírito Santo tem a missão, dentre outras, de nos guiar e sustentar nossa vida presente na senda da esperança (Mt 24:43; Lc 12:26)",
      "Quando Paulo diz: “e a vida que agora vivo na carne, vivo-a na fé do Filho de Deus” (Gl 2:20), faz referência ao seu novo modo de vida e o método eficaz de manter-se firme na fé é esperar pacientemente pela vida eterna que nos tem sido prometida (Rm 8:30). Pois não estamos falando de um mero objeto de desejo, temos esperança porque vivemos em esperança (Rm 8:24) e que é a nossa própria vida – Cristo (Cl 1:27). Ela entra em nossas vidas, em nossos corações como um dom de Deus a quem nós o tornamos como rocha e refúgio.",
      "Em termos pessoais a nossa relação com Deus inclui o nosso destino futuro o que nos obriga a uma reflexão na vida presente, pois andamos por fé, e não por vista (2 Co 5.7), e aí temos que administrar o tempo presente em função da eternidade que nos espera (2 Co 4.18). Nesse sentido a esperança escatológica não é simplesmente um balanço humano de probabilidades e previsões, nem tão pouco convencimento humano decorrente de uma busca por uma cadeia de raciocínio lógico (Hb 11:8-16).",
    ],
  },
  {
    slug: "o-legado-escatologico-do-apostolo-paulo",
    titulo: "O Legado Escatológico do Apóstolo Paulo",
    autor: "Pr Sebastião Otávio",
    paragrafos: [
      "A nossa cidadania, porém, está nos céus, de onde esperamos ansiosamente um Salvador, o Senhor Jesus Cristo - Filipenses 3:20",
      "É notório que as epístolas do Novo Testamento são registros do ensinamento apostólico na igreja primitiva, com fundamento, principalmente no Evangelho de Jesus Cristo, ensinos estes que segundo o relato de Lucas, ficaram notadamente conhecidos como a ”doutrina dos apóstolos” (At 2:42 - ARC). Os escritos são de Paulo, Pedro, João, Tiago, Judas e um anônimo.",
      "Quando sistematizado o pensamento apostólico sobre a volta de Jesus Cristo e os acontecimentos relacionados a sua segunda vinda, temos então um conjunto de doutrinas que entre si relacionam dentro do eterno propósito de Deus, abrangendo terra e céus, que dentro das Doutrinas Sistemáticas é chamada de Escatologia Bíblica.",
      "Tanto o salvo quanto o perdido, dentro da visão bíblica, aguardam o de estado de vida interminável, com apenas dois destinos finais. Para tanto, é imperioso o conhecimento de uma gama de assuntos tratados nas epístolas, como a segunda vinda de Jesus Cristo (arrebatamento e manifestação), a morte física, a imortalidade humana, o estado intermediário, a ressurreição dos salvos e dos perdidos, o novo corpo dos salvos, o tribunal de Cristo, as bodas do Cordeiro, a futura intervenção do Diabo na terra, do futuro reino de Cristo sobre a terra, o juízo do grande trono branco, o estado eterno e a da redenção da terra e céu.",
      "Tomando como exemplo os escritos do apóstolo Paulo, vemos que ele aborda uma série de assuntos escatológicos, a vida do apostolo Paulo foi marcada pelo dramático encontro com Jesus Cristo a caminho de Damasco. Encontro que colocou por terra todas as suas pretensões contra os nazarenos que ele mesmo tinha como alvo varrê-los do mundo romano. Paulo vê a sua crença, fé e autoridade cair por terra diante da declaração “Eu sou Jesus, a quem tu persegues. Duro é para ti recalcitrar contra os aguilhões” (At 9:5). A partir desse encontro ele se rende de maneira incondicional a Jesus Cristo e torna-se um dos mais ardorosos pregadores do Evangelho e apologista da “Verdade”. Razão pela qual Deus o tomou como ferramenta fundamental na formação dos “escritos” que compõem o Novo Testamento. Paulo discorreu sobre todas as doutrinas neotestamentárias contribuindo na formação da igreja no primeiro século.",
      "O legado doutrinário de Paulo encontra-se nas treze cartas que escreveu, de onde se pode extrair o pensamento escatológico e assim pontuar a visão escatológica que Paulo tinha a partir dos ensinos de Jesus Cristo e das revelações que recebeu.",
      "Primeiramente devemos ter em mente que ao escrever sobre o assunto em suas cartas, ele partia das necessidades dos cristãos, e sempre fazia com a intenção de instruir e esclarecer as igrejas. Paulo destaca que o crente individual, bem como a igreja como um todo, não encontrará sua perfeição ou estado completo nesta terra, e nem nesta existência terrena (1ª Co 13.12 e Rm 8.24). Antes de atingirmos o estado completo ou de perfeição, certo é que acontecimentos terão de ocorrer e de conformidade com o plano determinado por Deus antes da formação do mundo. Esses acontecimentos e o nosso estado futuro são abordados ou definidos na Doutrina das Últimas Coisas que abarca um conjunto de doutrinas que discorre sobre o porvir.",
      "A abordagem paulina não segue uma sequência lógica, como já dissemos que o fez diante dos questionamentos, da ignorância e dúvidas dos crentes e da própria ação do Espírito Santo tendo em vista a igreja de todas as épocas.",
    ],
  },
  {
    slug: "teologia-o-evangelho-e-salvacao",
    titulo: "Teologia, o Evangelho e Salvação",
    autor: "Pr Sebastião Otávio",
    paragrafos: [
      "No Livro “Você é Teólogo e Não Sabe”, o pastor Gunar Berg de Andrade faz a seguinte alusão: “Todo aquele que reflete, a respeito de questões essenciais do existir, pratica Teologia. Se estas indagações esbarram em questões que incluam o Criador, então esta pessoa é um teólogo”. Teologia, objetivamente ou ao pé da letra, se traduz pelo estudo de Deus (logia = estudo, Teo = Deus).",
      "Partindo deste raciocínio, ser teólogo é buscar entender a pessoa de Deus e a sua relação com o universo criado, pois teólogo é aquele que versa sobre Deus. Isto posto, todos os que aludem, falam ou abordam sobre Deus, são teólogos. Entretanto, tem aqueles que tratam, estudam e até mesmo são especialistas em teologia. Quando alguém está falando de Deus é preciso ter competência, habilidade e atitude correta, principalmente se for salvo em Jesus Cristo.",
      "Por outro lado, além da experiência pessoal com Jesus Cristo como o Senhor e Salvador, precisa crer e ter as Escrituras Sagradas como revelação divina, a priori do programa de Deus para a redenção da humanidade no pecado.",
      "Neste quesito, a Bíblia sem sombra de dúvida é a porta de entrada para nossa compreensão do plano de Deus para a salvação. Temos uma declaração no evangelho escrito por Lucas, que o próprio Senhor Jesus Cristo, após sua ressurreição, orientando seus discípulos, afirmou: “abriu-lhes o entendimento para compreenderem as Escrituras” (Lc 24:45). A mensagem do evangelho traz em si a revelação divina, ou seja, a vida, ministério e a obra da redenção na Palavra encarnada, na Palavra escrita, para tanto, a pregação do Evangelho é o anúncio da vida eterna que Jesus Cristo oferece em conformidade com as Escrituras.",
      "A pessoa que quer obter a salvação em Cristo não pode simplesmente se valer das ciências humanas, estudadas pelos meios humanos que o homem dispõe, e que não vai além da capacidade humana. Entretanto, quando se trata das Escrituras Sagradas, a Bíblia, é uma ciência divina e que necessariamente é imperioso o conhecimento espiritual, ou seja, o discernimento para a salvação é uma operação divina do Espirito Santo, por meio da pregação do Evangelho.",
      "Quando lemos os evangelhos e o livro dos Atos dos Apóstolos, tanto o Senhor Jesus Cristo no seu ministério terreno, bem como a igreja no primeiro século, tinham como compromisso anunciar o evangelho da salvação. Razão pela qual Marcos registra “veio Jesus para a Galileia, pregando o Evangelho do Reino de Deus” (Mc 1:14) e a premissa era que cressem nesta mensagem salvadora e certo é que os escritos do Novo Testamento registram que muitas pessoas compreenderam esta mensagem gloriosa e receberam o dom da graça de Deus, a vida eterna.",
      "Quando temos em mente que a salvação do pecador, depende da pregação e do ensino do Evangelho de Jesus Cristo, aquele que evangeliza e discípula necessariamente tem o dever de conhecer a contento “o evangelho de Cristo, pois é o poder de Deus” e neste quesito temos o desafio de ensinar Teologia, e esta deve ser a premissa do ensino teológico, quer nas EBD’s (Escolas Bíblicas Dominicais), Institutos Teológicos ou Escolas de Educação Teológica.",
    ],
  },
  {
    slug: "venha-o-teu-reino",
    titulo: "Venha o Teu Reino",
    autor: "Pr Edney Rocha",
    paragrafos: [
      "Em Mateus 6:10 o Senhor Jesus ensina os discípulos a orar dizendo entre outras coisas, \"venha o teu Reino. Seja feita a tua vontade na terra como no céu...”. Para melhor entender vamos pensar um pouco nos hebreus (Israel). A Bíblia diz em Dt 7.7-8; Lv 20.26; Dt 10.12,13, que Deus chamou os hebreus, os escolheu, para serem seu povo, para O servir, para serem seus servos. Vemos isso no modelo do concerto, ou aliança de Deus com eles no Sinai (Ex 19), aqui Deus se mostra como Senhor e Rei e o povo, Israel, seus vassalos. Eles recebem normas para que saibam como agradar a Deus, como e quando se achegarem à Ele e lhe prestarem culto. Eles precisavam entender que estavam debaixo da vontade e do governo Divino.",
      "Quando o Senhor Jesus ensina os discípulos, em oração pedirem, \"Venha o teu Reino\", Ele estava querendo que nós, seguidores de Cristo, a exemplo da Aliança de Deus com Israel, invoquemos e reconheçamos a vontade e governo de Deus sobre nossas vidas, afinal, Jesus inicia seu ministério pregando: “... é chegado (ou está aqui) o Reino de Deus...\" (Mt 4.17; Mc 1.15). A pregação do Evangelho está estreitamente ligada ao Reino de Deus. De maneira que a palavra grega \"Basiléia\" (Reino) aparece 144 vezes no Novo Testamento (Dicionário de Teologia do Novo Testamento, 2000, p. 2035). Nessas citações encontramos 111 nos evangelhos Sinóticos (Mateus: 52 vezes; Marcos: 16 e Lucas: 43 vezes). Em João, aparece cerca de cinco vezes. O apóstolo Paulo faz 19 citações, sendo cinco vezes em Atos e outras 14 nas cartas Paulinas. No livro do Apocalipse, existem duas citações e nos demais escritos do NT, mais de sete vezes, totalizando 144 referências à Basiléia (Reino) no NT.",
      "O Senhor nos escolheu e nos nomeou, conforme Jo 15.16. Ele fez uma Nova Aliança conosco (Hb 8) para que possamos fazer parte do Reino de Deus, e não somente isso, sermos herdeiros do Reino (Mt 25.34). Para tanto, hoje precisamos viver o Reino de Deus que veio na pessoa de Cristo e que será na sua plenitude, na segunda vinda de Jesus. Como igreja de Cristo, vivemos o Reino de Deus e não somente isso, somos sacerdócio real. Na primeira carta de Pedro 2.9, constatamos que temos a função e ordem de conduzir pessoas à presença do rei Jesus através da pregação do Evangelho (Mt 28.18-20; Mc 16.15). Venha o Teu Reino, essa é a sua oração?",
    ],
  },
];

export function getArtigoBySlug(slug: string): Artigo | undefined {
  return artigos.find((a) => a.slug === slug);
}

export function resumo(artigo: Artigo, max = 160): string {
  const texto = artigo.paragrafos[0] ?? "";
  if (texto.length <= max) return texto;
  return texto.slice(0, max).trimEnd() + "…";
}
